package com.neo4j.tools.certtool.output;

import com.neo4j.tools.certtool.CertificateGenerator.NodeBundle;
import com.neo4j.tools.certtool.CertificateGenerator.ScopeMaterial;
import com.neo4j.tools.certtool.model.Scope;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.Arrays;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;

/**
 * Renders the {@code neo4j.conf} settings that activate the generated material.
 *
 * <p>Only settings whose values follow directly from what was generated are emitted uncommented.
 * Anything that is a deployment choice — cipher suites, TLS versions — is included as a commented
 * suggestion so that merging the snippet cannot silently change a working cluster's negotiation
 * parameters.
 */
public final class ConfSnippet {

    private static final DateTimeFormatter TIMESTAMP =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss 'UTC'").withZone(ZoneOffset.UTC);

    private ConfSnippet() {}

    /**
     * Builds the snippet for one node.
     *
     * @param password the private key password, which Neo4j requires in clear text; may be null
     *     when keys were written unencrypted
     */
    public static void writeTo(
            OutputStream out, NodeBundle bundle, char[] password, Instant generatedAt)
            throws IOException {
        StringBuilder text = new StringBuilder();
        text.append("# Neo4j SSL policy configuration for node '")
                .append(bundle.node().name())
                .append("'\n");
        text.append("# Generated by neo4j-cert-tool at ").append(TIMESTAMP.format(generatedAt)).append('\n');
        text.append("#\n");
        text.append("""
                # To apply:
                #   1. Copy this node's 'certificates' directory to <neo4j-home>/certificates
                #      (preserving permissions, e.g. 'rsync -a' or 'scp -rp').
                #   2. chown -R neo4j:neo4j <neo4j-home>/certificates
                #   3. Merge the settings below into <neo4j-home>/conf/neo4j.conf.
                #   4. Restart the instance. From Neo4j 2025.03 onwards certificates can be
                #      rotated without a restart, but enabling a policy for the first time
                #      still requires one.
                #
                # This file contains a private key password in clear text, which is how Neo4j
                # reads it. Keep neo4j.conf readable only by the Neo4j service user:
                #   chown neo4j:neo4j <neo4j-home>/conf/neo4j.conf && chmod 640 <neo4j-home>/conf/neo4j.conf
                """);

        for (ScopeMaterial material : bundle.scopes()) {
            Scope scope = material.scope();
            String prefix = scope.configPrefix();
            text.append("\n# --- ").append(scope.directoryName()).append(": ").append(scope.purpose()).append(" ---\n");
            text.append(prefix).append(".enabled=true\n");
            text.append(prefix).append(".base_directory=certificates/").append(scope.directoryName()).append('\n');
            text.append(prefix).append(".private_key=private.key\n");
            text.append(prefix).append(".public_certificate=public.crt\n");
            text.append(prefix).append(".trusted_dir=trusted\n");
            text.append(prefix).append(".revoked_dir=revoked\n");
            if (password != null) {
                // The surrounding text is written out first so the password can go straight to the
                // stream. Appending it to the StringBuilder would leave it in the builder's backing
                // array and in the String that toString() produces, neither of which can be zeroed.
                text.append(prefix).append(".private_key_password=");
                flush(out, text);
                writeSecret(out, password);
                text.append('\n');
            }
            if (scope.mutualAuthentication()) {
                text.append(prefix).append(".client_auth=REQUIRE\n");
                // Only meaningful where the instance acts as a TLS client, which is exactly the
                // mutually authenticated scopes. Every peer address is in the certificate's SAN.
                text.append(prefix).append(".verify_hostname=true\n");
            } else {
                // Drivers and browsers do not present client certificates.
                text.append(prefix).append(".client_auth=NONE\n");
            }
            text.append("# ").append(prefix).append(".tls_versions=TLSv1.3,TLSv1.2\n");
            text.append("# ").append(prefix).append(".ciphers=<comma-separated suites>\n");
        }

        if (bundle.scopes().stream().anyMatch(m -> m.scope() == Scope.BOLT)) {
            text.append("""

                    # Bolt also needs TLS switched on for the connector itself:
                    server.bolt.tls_level=REQUIRED
                    """);
        }
        if (bundle.scopes().stream().anyMatch(m -> m.scope() == Scope.HTTPS)) {
            text.append("""

                    # And the HTTPS connector has to be enabled:
                    server.https.enabled=true
                    # server.http.enabled=false
                    """);
        }
        flush(out, text);
    }

    /** Writes the accumulated non-secret text and empties the builder. */
    private static void flush(OutputStream out, StringBuilder text) throws IOException {
        out.write(text.toString().getBytes(StandardCharsets.UTF_8));
        text.setLength(0);
    }

    /**
     * Writes a password to the stream, zeroing the encoded bytes afterwards.
     *
     * <p>The file itself necessarily holds the password in clear text, since that is how Neo4j
     * reads it. This only avoids leaving additional copies on the heap.
     */
    private static void writeSecret(OutputStream out, char[] password) throws IOException {
        ByteBuffer encoded = StandardCharsets.UTF_8.encode(CharBuffer.wrap(password));
        byte[] bytes = new byte[encoded.remaining()];
        encoded.get(bytes);
        try {
            out.write(bytes);
        } finally {
            Arrays.fill(bytes, (byte) 0);
            if (encoded.hasArray()) {
                Arrays.fill(encoded.array(), (byte) 0);
            }
        }
    }

    /** The warning written alongside a generated CA's private key. */
    public static String caReadme() {
        return """
            This directory holds the certificate authority for the cluster.

            The private key here can issue a certificate that every cluster member will
            trust. Treat it as the most sensitive material the cluster has:

              * Move it off this machine. It is not needed on any cluster member; only the
                per-node bundles are.
              * Keep it somewhere with restricted access and a backup, such as a secrets
                manager or offline encrypted storage.
              * Keep the password with it, stored separately from the key itself.

            To add or replace a node later, bring the CA back and issue for the new node
            without touching the existing members:

              neo4j-cert-tool --node <name>:<dns>,<ip> \\
                --ca-cert ca.crt --ca-key ca.key --out ./new-node

            The new node's trusted/root-ca.crt will match what the existing nodes already
            trust, so nothing on them has to change.
            """;
    }
}
